version: "3.9"
services:

  # DATA CONNECT
  data-connect:
    image: ga4gh/ga4gh-starter-kit-data-connect:test
    hostname: dataconnect.starterkit.ga4gh.org
    ports:
      - "4500:4500"

  # PASSPORT

  # DRS
  drs-migrate:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.1
    volumes:
      - "./resources/drs/db:/db"
    command: database create-tables -d jdbc:sqlite:/db/drs.db drs@v0.3.1
  drs-dataset:
    depends_on:
      - drs-migrate
    image: ga4gh/ga4gh-starter-kit-utils:0.1.1
    volumes:
      - "./resources/drs/db:/db"
    command: database add-test-dataset -d jdbc:sqlite:/db/drs.db drs@v0.3.1
  drs:
    depends_on:
      - drs-migrate
      - drs-dataset
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    hostname: drs.starterkit.federatedgenomics.org
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./resources/drs/config:/config"
      - "./resources/drs/db:/db"
    command: -c /config/config.yml
